Fix tests on Travis CI fail randomly
Builds randomly fail with

```bash
> NODE_PATH=. babel-node `which tape` 'src/**/*.test.js' | faucet
module.js:491
    throw err;
    ^
Error: Cannot find module '/home/travis/build/lunohodov/pokemail/src/**/*.test.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /home/travis/build/lunohodov/pokemail/node_modules/faucet/node_modules/tape/bin/tape:5:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/travis/build/lunohodov/pokemail/node_modules/faucet/node_modules/tape/bin/tape:4:23)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js]
(/home/travis/build/lunohodov/pokemail/node_modules/babel-register/lib/node.js:152:7)
```

It seems some dependencies in `node bin` are not available when the
build starts.

Using NPM for dependency management solves the problem.

This commit also reduced dependencies by switching from Yarn to NPM.